config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :photos
  resources :home, only: [:index]
  resources :image_attachments do
    resources :comments
    resources :tags
  end
  resources :posts
end

app/models/image_attachment.rb
class ImageAttachment < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :post
  has_many :comments
  has_many :tags
end

app/controllers/image_attachments_controller.rb
class ImageAttachmentsController < ApplicationController

  def destroy
    @photo = ImageAttachment.find(params[:id])
    @post = @photo.post
    @photo.destroy
    redirect_to post_path(@post)
  end

  def update
    respond_to do |format|
      if @image_attachment.update(image_attachment_params)
        format.html { redirect_to @image_attachment.image, notice: 'Your image attachment was successfully updated.' }
      end
    end
  end

  def show
    @photo = ImageAttachment.find(params[:id])
  end

end

app/views/image_attachments/show.html.erb
<h1><%= @photo.post.title %></h1>
<img src="<%= @photo.photo %>">

<% @photo.comments.each do |comment|%>
  <p><%= comment.user_id %></p>
  <p><%= comment.user_comment %></p>
  <%= link_to 'Delete', image_attachment_comment_path(@photo, comment), data: {confirm: 'Are you sure?', method: 'delete'} %>
  <%= link_to 'Edit', edit_image_attachment_comment_path(@photo, comment) %>
<% end %>

<% @photo.tags.each do |tag| %>
  <p><%= tag.name %></p>
  <%= link_to 'Delete', image_attachment_tag_path(@photo, tag), data: {confirm: 'Are you sure?', method: 'delete'} %>
<% end %>

<%= link_to 'Add a Tag', new_image_attachment_tag_path(@photo) %> |
<%= link_to "Add a Comment", new_image_attachment_comment_path(@photo) %>