config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :photos
  resources :home, only: [:index]
  resources :image_attachments do
    resources :comments
    resources :tags
  end
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :image_attachments
  accepts_nested_attributes_for :image_attachments
  belongs_to :user
  has_many (:comments), through: :image_attachments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
   @user = current_user
   @posts = @user.posts
end

def show
   @post = Post.find(params[:id])
   @image_attachments = @post.image_attachments.all
end

def new
   @post = Post.new
   @image_attachment = @post.image_attachments.new
end

def create
   @post = Post.new(post_params)
   @post.update_attribute(:user_id, current_user.id)
   if @post.save
     params[:image_attachments]['photo'].each do |a|
        @image_attachment = @post.image_attachments.create(:photo => a)
     end
     redirect_to @post
     flash['notice'] = 'Post was successfully created.'
   else
     render 'new'
   end
 end

 def edit
   @post = Post.find(params[:id])
 end

def update
  @post = Post.find(params[:id])
  if @post.update(post_params)
    params[:image_attachments]['photo'].each do |a|
       @image_attachment = @post.image_attachments.create(:photo => a)
    end
    redirect_to post_path(@post)
    flash['notice'] = 'Post was successfully updated.'
  else
    render :edit
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

 private
   def post_params
      params.require(:post).permit(:title, image_attachments_attributes: [:id, :post_id, :photo])
   end

end

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
   <div class="field">
     <%= f.label :title %><br>
     <%= f.text_field :title %>
   </div>

   <%= f.fields_for :image_attachments do |p| %>
     <div class="field">
       <%= p.label :photo %><br>
       <%= p.file_field :photo, :multiple => true, name: "image_attachments[photo][]" %>
     </div>
   <% end %>

   <div class="actions">
     <%= f.submit %>
   </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

<%= link_to 'New', new_post_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<% @image_attachments.each do |photo| %>
  <%= link_to image_attachment_path(photo) do %>
    <%= image_tag photo.photo_url %>
  <% end %>
  <%= link_to "Edit Photo", edit_image_attachment_path(photo) %>
  <%= link_to "Delete Photo", image_attachment_path(photo), data: {confirm: "Are you sure?", method: 'delete'} %>
<% end %>

<%= link_to 'Delete this Post', post_path(@post), data: {confirm: "Are you sure?", method: 'delete'} %>
<%= link_to 'Edit this Post', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>